In [ ]:
# Joins
import pandas as pd

# Table 1: Passenger Names
df_names = pd.DataFrame({
    'PassengerId': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})
print(df_names)

# Table 2: Ticket Prices
df_prices = pd.DataFrame({
    'PassengerId': [1, 2, 4],
    'Fare': [50.00, 80.00, 100.00]
})

# here display function display same like a table structure
display(df_prices)

   PassengerId     Name
0            1    Alice
1            2      Bob
2            3  Charlie

   PassengerId   Fare
0            1   50.0
1            2   80.0
2            4  100.0

In [11]:
df_names

   PassengerId     Name
0            1    Alice
1            2      Bob
2            3  Charlie

In [12]:
df_prices

   PassengerId   Fare
0            1   50.0
1            2   80.0
2            4  100.0

In [ ]:
# Joining tables
# inner joins (display only common data) similar to intersection in sets
pd.merge(df_names, df_prices, on='PassengerId', how='inner')

   PassengerId   Name  Fare
0            1  Alice  50.0
1            2    Bob  80.0

In [15]:
#Left Join display only left side table data(if ids match data display not displayed null(NAN) values)
pd.merge(df_names, df_prices, on='PassengerId', how='left')

   PassengerId     Name  Fare
0            1    Alice  50.0
1            2      Bob  80.0
2            3  Charlie   NaN

In [16]:
# Right join(it will disaply right side table if ids match data displayed if not NAN values)
pd.merge(df_names, df_prices, on='PassengerId', how='right')

   PassengerId   Name   Fare
0            1  Alice   50.0
1            2    Bob   80.0
2            4    NaN  100.0

In [5]:
# Advanced Transformations
# 1. Data Type Casting (.astype()) -> 'float', 'int', 'str'
# 2. Text Cleaning (.str accessor) -> .str.strip() to remove blank spaces at beginning or end, .str.lower(), .str.upper()

import pandas as pd

df_messy = pd.DataFrame({
     'Passenger': [' Alice ', 'Bob', 'Charlie '],
     'TicketCode': [101, 102, 103]
})

df_messy

  Passenger  TicketCode
0    Alice          101
1       Bob         102
2  Charlie          103

In [ ]:
# 1. Fix the TicketCode (Data Type Casting) int to str

df_messy['TicketCode'] = df_messy['TicketCode'].astype('str')
df_messy

  Passenger TicketCode
0    Alice         101
1       Bob        102
2  Charlie         103

In [8]:
# 2. Clean the Passenger Names (Text Cleaning)
df_messy['Passenger'] = df_messy['Passenger'].str.strip()

In [9]:
df_messy.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Passenger   3 non-null      str
 1   TicketCode  3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [13]:
# Setup our family dataset
family_data = {
    'Passenger': ['Alice', 'Bob', 'Charlie'],
    'SibSp': [1, 0, 2], # Number of Siblings or Spouses aboard
    'Parch': [1, 0, 1]  # Number of Parents or Children aboard
}
df_family = pd.DataFrame(family_data)
df_family

  Passenger  SibSp  Parch
0     Alice      1      1
1       Bob      0      0
2   Charlie      2      1

In [14]:
# 1.Your manager wants to know the Total Family Size for each passenger. Total family size is calculated by adding the SibSp column to the Parch column.
df_family['TotalFamily'] = df_family['SibSp'] + df_family['Parch']

In [16]:
df_family

  Passenger  SibSp  Parch  TotalFamily
0     Alice      1      1            2
1       Bob      0      0            0
2   Charlie      2      1            3

In [17]:
# 2: Aggregations (.groupby)

# Setup our aggregation dataset
agg_data = {
    'Pclass': [1, 1, 2, 2, 3, 3], # Passenger Class
    'Fare': [100.0, 150.0, 50.0, 60.0, 10.0, 15.0] # Ticket Price
}
df_agg = pd.DataFrame(agg_data)
df_agg

   Pclass   Fare
0       1  100.0
1       1  150.0
2       2   50.0
3       2   60.0
4       3   10.0
5       3   15.0

In [18]:
# What was the average ticket fare for each passenger class?
df_agg.groupby('Pclass')['Fare'].mean()

Pclass
1    125.0
2     55.0
3     12.5
Name: Fare, dtype: float64