In [ ]:
# Joins
import pandas as pd

# Table 1: Passenger Names
df_names = pd.DataFrame({
    'PassengerId': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})
print(df_names)

# Table 2: Ticket Prices
df_prices = pd.DataFrame({
    'PassengerId': [1, 2, 4],
    'Fare': [50.00, 80.00, 100.00]
})

# here display function display same like a table structure
display(df_prices)

   PassengerId     Name
0            1    Alice
1            2      Bob
2            3  Charlie

   PassengerId   Fare
0            1   50.0
1            2   80.0
2            4  100.0

In [11]:
df_names

   PassengerId     Name
0            1    Alice
1            2      Bob
2            3  Charlie

In [12]:
df_prices

   PassengerId   Fare
0            1   50.0
1            2   80.0
2            4  100.0

In [ ]:
# Joining tables
# inner joins (display only common data) similar to intersection in sets
pd.merge(df_names, df_prices, on='PassengerId', how='inner')

   PassengerId   Name  Fare
0            1  Alice  50.0
1            2    Bob  80.0

In [15]:
#Left Join display only left side table data(if ids match data display not displayed null(NAN) values)
pd.merge(df_names, df_prices, on='PassengerId', how='left')

   PassengerId     Name  Fare
0            1    Alice  50.0
1            2      Bob  80.0
2            3  Charlie   NaN

In [16]:
# Right join(it will disaply right side table if ids match data displayed if not NAN values)
pd.merge(df_names, df_prices, on='PassengerId', how='right')

   PassengerId   Name   Fare
0            1  Alice   50.0
1            2    Bob   80.0
2            4    NaN  100.0