In [17]:
import pandas as pd
# ==========================================
# 📤 1. EXTRACT (Load raw data into Pandas)
# ==========================================
# Normally this is pd.read_csv('file.csv'), but we will create dummy data here
df_orders = pd.DataFrame({
    'OrderID': [1, 2, 3, 4, 5],
    'Product': [' Laptop ', 'Mouse', 'Keyboard ', ' Monitor', 'Laptop'],
    'Quantity': [1, 2, 1, 2, 2],
    'PriceString': ['1000.0', '25.5', '45.0', '200.0', '2000.0'] # Uh oh, these are text!
})

df_orders

   OrderID    Product  Quantity PriceString
0        1    Laptop          1      1000.0
1        2      Mouse         2        25.5
2        3  Keyboard          1        45.0
3        4    Monitor         2       200.0
4        5     Laptop         2      2000.0

In [18]:
# ==========================================
# 🧹 2. TRANSFORM (Clean the mess)
# ==========================================
# Strip accidental blank spaces from the product names
df_orders['Product'] = df_orders['Product'].str.strip()
df_orders

   OrderID   Product  Quantity PriceString
0        1    Laptop         1      1000.0
1        2     Mouse         2        25.5
2        3  Keyboard         1        45.0
3        4   Monitor         2       200.0
4        5    Laptop         2      2000.0

In [19]:
# Cast the 'PriceString' column from text to float (decimals) so we can do math
df_orders['Price'] = df_orders['PriceString'].astype('float')
df_orders

   OrderID   Product  Quantity PriceString   Price
0        1    Laptop         1      1000.0  1000.0
1        2     Mouse         2        25.5    25.5
2        3  Keyboard         1        45.0    45.0
3        4   Monitor         2       200.0   200.0
4        5    Laptop         2      2000.0  2000.0

In [20]:
# ==========================================
# 🛠️ 3. FEATURE ENGINEERING (Create new data)
# ==========================================
# Create a 'Total_Sales' column by multiplying Quantity by the cleaned Price
df_orders['Total_Sales'] = df_orders['Quantity'] * df_orders['Price']
df_orders

   OrderID   Product  Quantity PriceString   Price  Total_Sales
0        1    Laptop         1      1000.0  1000.0       1000.0
1        2     Mouse         2        25.5    25.5         51.0
2        3  Keyboard         1        45.0    45.0         45.0
3        4   Monitor         2       200.0   200.0        400.0
4        5    Laptop         2      2000.0  2000.0       4000.0

In [21]:
# ==========================================
# 📊 4. AGGREGATE (Summarize for the Boss)
# ==========================================
# Group by Product to see the total money made per item
df_summary = df_orders.groupby('Product')['Total_Sales'].sum().reset_index()
df_summary

    Product  Total_Sales
0  Keyboard         45.0
1    Laptop       5000.0
2   Monitor        400.0
3     Mouse         51.0