In [1]:
import pandas as pd
import duckdb

df_sales = pd.DataFrame({
    'RepName': ['John', 'Alice', 'Bob', 'Emma', 'Liam'],
    'Region': ['North', 'North', 'North', 'South', 'South'],
    'Sales': [10000, 15000, 10000, 20000, 18000]
})

df_sales

  RepName Region  Sales
0    John  North  10000
1   Alice  North  15000
2     Bob  North  10000
3    Emma  South  20000
4    Liam  South  18000

In [ ]:
#Write a SQL query that displays the RepName, Region, Sales, and a new calculated column called Regional_Rank.
#Use DENSE_RANK() to calculate the rank.
#The rank should reset for every new Region.
#The person with the highest sales in that region should get Rank 1.

query_C = """
SELECT 
    RepName,
    Region,
    Sales,
    DENSE_RANK() OVER (PARTITION BY Region ORDER BY Sales DESC) AS Regional_Rank
FROM df_sales;
"""

duckdb.query(query_C).df()
# PARTITION BY means GROUP BY

  RepName Region  Sales  Regional_Rank
0    Emma  South  20000              1
1    Liam  South  18000              2
2   Alice  North  15000              1
3    John  North  10000              2
4     Bob  North  10000              2

In [3]:
# Your Task: 1. Filter the data so you are only looking at sensors where the Status is exactly 'Active'.
# 2. Create a Temperature_Rank column using a Window Function. Rank the temperatures from highest to lowest, but restart the ranking for each individual City.

import pandas as pd

df_sensors = pd.DataFrame({
    'City': ['Tokyo', 'Kyoto', 'Tokyo', 'Tokyo', 'Kyoto', 'Kyoto'],
    'SensorID': ['T-1', 'K-1', 'T-2', 'T-3', 'K-2', 'K-3'],
    'Status': ['Active', 'Active', 'Offline', 'Active', 'Active', 'Offline'],
    'Temperature': [39.0, 35.0, 99.9, 37.2, 38.5, -99.9]
})

df_sensors

    City SensorID   Status  Temperature
0  Tokyo      T-1   Active         39.0
1  Kyoto      K-1   Active         35.0
2  Tokyo      T-2  Offline         99.9
3  Tokyo      T-3   Active         37.2
4  Kyoto      K-2   Active         38.5
5  Kyoto      K-3  Offline        -99.9

In [5]:
import duckdb

query_1 = """
SELECT
    City,
    SensorID,
    Temperature,
    DENSE_RANK() OVER(PARTITION BY City ORDER BY Temperature DESC) AS Temperature_Rank
FROM df_sensors
WHERE Status = 'Active';
"""
duckdb.query(query_1).df()

    City SensorID  Temperature  Temperature_Rank
0  Tokyo      T-1         39.0                 1
1  Tokyo      T-3         37.2                 2
2  Kyoto      K-2         38.5                 1
3  Kyoto      K-1         35.0                 2

In [6]:
import pandas as pd
import duckdb

df_server = pd.DataFrame({
    'Date': ['2026-06-01', '2026-06-02', '2026-06-03', '2026-06-04'],
    'Traffic': [500, 550, 800, 750]
})

query_F = """
SELECT 
    Date,
    Traffic,
    LAG(Traffic) OVER (ORDER BY Date) AS Previous_Traffic,
    Traffic - LAG(Traffic) OVER (ORDER BY Date) AS Traffic_Spike
FROM df_server;
"""

duckdb.query(query_F).df()

         Date  Traffic  Previous_Traffic  Traffic_Spike
0  2026-06-01      500              <NA>           <NA>
1  2026-06-02      550               500             50
2  2026-06-03      800               550            250
3  2026-06-04      750               800            -50

In [8]:
import pandas as pd

df_storage = pd.DataFrame({
    'Date': ['2026-06-01', '2026-06-02', '2026-06-03', '2026-06-04'],
    'Daily_GB': [50, 120, 80, 200]
})

df_storage

         Date  Daily_GB
0  2026-06-01        50
1  2026-06-02       120
2  2026-06-03        80
3  2026-06-04       200

In [9]:
import duckdb

query_storage = """
SELECT
    Date,
    Daily_GB,
    SUM(Daily_GB) OVER(ORDER BY DATE ASC) AS Cumulative_GB
FROM df_storage;
"""
duckdb.query(query_storage).df()

         Date  Daily_GB  Cumulative_GB
0  2026-06-01        50           50.0
1  2026-06-02       120          170.0
2  2026-06-03        80          250.0
3  2026-06-04       200          450.0

In [1]:
import pandas as pd

df_signups = pd.DataFrame({
    'Date': ['2026-06-08', '2026-06-09', '2026-06-10', '2026-06-08', '2026-06-09', '2026-06-10'],
    'Platform': ['React Web', 'React Web', 'React Web', 'Java Mobile', 'Java Mobile', 'Java Mobile'],
    'New_Users': [300, 50, 100, 100, 150, 200]
})
df_signups

         Date     Platform  New_Users
0  2026-06-08    React Web        300
1  2026-06-09    React Web         50
2  2026-06-10    React Web        100
3  2026-06-08  Java Mobile        100
4  2026-06-09  Java Mobile        150
5  2026-06-10  Java Mobile        200

In [12]:
import duckdb

query_signups = """
SELECT
    Date,
    Platform,
    New_Users,
    SUM(New_Users) OVER(PARTITION BY Platform ORDER BY Date ASC) AS Cummulative_Users
FROM df_signups;
"""
duckdb.query(query_signups).df()

         Date     Platform  New_Users  Cummulative_Users
0  2026-06-08  Java Mobile        100              100.0
1  2026-06-09  Java Mobile        150              250.0
2  2026-06-10  Java Mobile        200              450.0
3  2026-06-08    React Web        300              300.0
4  2026-06-09    React Web         50              350.0
5  2026-06-10    React Web        100              450.0

In [13]:
import pandas as pd
import duckdb

df_jobs = pd.DataFrame({
    'Company': ['Google', 'Google', 'Google', 'Meta', 'Meta'],
    'Job_Title': ['React Developer', 'React Developer', 'Node.js Engineer', 'Full Stack Engineer', 'Full Stack Engineer'],
    'Date_Posted': ['2026-06-01', '2026-06-01', '2026-06-05', '2026-06-02', '2026-06-02']
})

df_jobs

  Company            Job_Title Date_Posted
0  Google      React Developer  2026-06-01
1  Google      React Developer  2026-06-01
2  Google     Node.js Engineer  2026-06-05
3    Meta  Full Stack Engineer  2026-06-02
4    Meta  Full Stack Engineer  2026-06-02

In [21]:
query_J = """
SELECT
    COMPANY,
    JOB_TITLE,
    DATE_POSTED,
    ROW_NUMBER() OVER(PARTITION BY COMPANY, JOB_TITLE ORDER BY DATE_POSTED ASC) AS Row_ID
FROM df_jobs;
"""

duckdb.query(query_J).df()

  Company            Job_Title Date_Posted  Row_ID
0  Google     Node.js Engineer  2026-06-05       1
1    Meta  Full Stack Engineer  2026-06-02       1
2    Meta  Full Stack Engineer  2026-06-02       2
3  Google      React Developer  2026-06-01       1
4  Google      React Developer  2026-06-01       2

In [ ]:
import pandas as pd

df_clicks = pd.DataFrame({
    'UserID': ['U-101', 'U-101', 'U-101', 'U-102', 'U-102'],
    'Timestamp': ['09:00', '09:05', '09:10', '10:15', '10:20'],
    'Current_Page': ['/home', '/pricing', '/checkout', '/home', '/docs']
})
df_clicks

  UserID Timestamp Current_Page
0  U-101     09:00        /home
1  U-101     09:05     /pricing
2  U-101     09:10    /checkout
3  U-102     10:15        /home
4  U-102     10:20        /docs

In [7]:
# Write a query to calculate the Next_Page.
# Use LEAD() to look forward.
# Use PARTITION BY so you don't accidentally mix up User 1's journey with User 2's journey!
# Use ORDER BY to make sure time is moving forward chronologically.

import duckdb
query_nextpage = """
SELECT
    Userid,
    timestamp,
    current_page,
    Lead(current_page) OVER(partition by userid order by timestamp asc) AS Next_Page
FROM df_clicks;
"""

duckdb.query(query_nextpage).df()

  UserID Timestamp Current_Page  Next_Page
0  U-101     09:00        /home   /pricing
1  U-101     09:05     /pricing  /checkout
2  U-101     09:10    /checkout        NaN
3  U-102     10:15        /home      /docs
4  U-102     10:20        /docs        NaN

In [4]:
import pandas as pd

df_performance = pd.DataFrame({
    'Server_ID': ['Server_1', 'Server_1', 'Server_1', 'Server_2', 'Server_2'],
    'Timestamp': ['08:00', '08:05', '08:10', '09:00', '09:15'],
    'Latency_ms': [250, 45, 50, 300, 60]
})

df_performance

  Server_ID Timestamp  Latency_ms
0  Server_1     08:00         250
1  Server_1     08:05          45
2  Server_1     08:10          50
3  Server_2     09:00         300
4  Server_2     09:15          60

In [ ]:
# The database groups all the logs for Server A.
# It sorts them chronologically.
# It looks at the very first row, sees a latency of 150ms, and permanently holds that number in its memory.
# As it walks down the rest of the rows for Server A, it pastes 150ms next to every single one.
import duckdb
query_latency = """
SELECT
    server_id,
    timestamp,
    latency_ms,
    FIRST_VALUE(latency_ms) OVER(PARTITION BY SERVER_ID ORDER BY TIMESTAMP ASC) AS Baseline_Latency
FROM df_performance;
"""
duckdb.query(query_latency).df()

  Server_ID Timestamp  Latency_ms  Baseline_Latency
0  Server_1     08:00         250               250
1  Server_1     08:05          45               250
2  Server_1     08:10          50               250
3  Server_2     09:00         300               300
4  Server_2     09:15          60               300

# NTILE()
#### Imagine you have a list of people sorted by their test scores.Instead of giving them individual rank numbers (1st place, 2nd place), NTILE(x) chops that list into x equal-sized buckets.
#### In the real world, the Marketing or Sales teams don't want to look at 10,000 individual users. They want to group people into tiers so they can take action.
#### 1. "Give me the Top 10% of spenders so we can send them a VIP gift." -> NTILE(10)
#### 2. "Divide our servers into 3 tiers (Fast, Normal, Slow)." -> NTILE(3)
#### 3. "Split our students into Quartiles (Top 25%, etc.)." -> NTILE(4)

In [8]:
import pandas as pd

df_customers = pd.DataFrame({
    'Customer_Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Fiona'],
    'Total_Spend': [1000, 300, 100, 800, 500, 50]
})
df_customers

  Customer_Name  Total_Spend
0         Alice         1000
1           Bob          300
2       Charlie          100
3         David          800
4           Eve          500
5         Fiona           50

In [10]:
# You are preparing a dataset for the marketing team. They want to send out three different email campaigns: a VIP promo, a Standard promo, 
# and a Re-engagement promo. They need you to divide all the customers into exactly 3 tiers based on their total lifetime spending.

import duckdb

query_ntile = """
SELECT
    Customer_Name,
    Total_Spend,
    NTILE(3) OVER(ORDER BY total_spend DESC) AS Customer_Tier
FROM df_customers;
"""
duckdb.query(query_ntile).df()

  Customer_Name  Total_Spend  Customer_Tier
0         Alice         1000              1
1         David          800              1
2           Eve          500              2
3           Bob          300              2
4       Charlie          100              3
5         Fiona           50              3

# LAST_VALUE()
#### similar to FIRST_VALUE() but just opposite

In [11]:
import pandas as pd

df_routes = pd.DataFrame({
    'Driver': ['Driver_A', 'Driver_A', 'Driver_A', 'Driver_B', 'Driver_B'],
    'Time': ['08:00', '08:30', '09:00', '10:00', '11:00'],
    'Stop_Name': ['Warehouse', 'Coffee Shop', 'Post Office', 'Warehouse', 'Gas Station']
})

df_routes

     Driver   Time    Stop_Name
0  Driver_A  08:00    Warehouse
1  Driver_A  08:30  Coffee Shop
2  Driver_A  09:00  Post Office
3  Driver_B  10:00    Warehouse
4  Driver_B  11:00  Gas Station

In [15]:
# You are analyzing delivery driver routes. The Logistics Manager wants a report that shows every stop a driver made, 
# but they also want a column showing the driver's Final Destination on that exact same row.

import duckdb
query_fd = """
SELECT
    Driver,
    Time,
    Stop_Name,
    LAST_VALUE(Stop_Name) OVER(
        PARTITION BY Driver
        ORDER BY Time ASC
        ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS Final_Destination
FROM df_routes;
"""

duckdb.query(query_fd).df()

     Driver   Time    Stop_Name Final_Destination
0  Driver_B  10:00    Warehouse       Gas Station
1  Driver_B  11:00  Gas Station       Gas Station
2  Driver_A  08:00    Warehouse       Post Office
3  Driver_A  08:30  Coffee Shop       Post Office
4  Driver_A  09:00  Post Office       Post Office

In [ ]:
# You are analyzing delivery driver routes. The Logistics Manager wants a report that shows every stop a driver made, 
# but they also want a column showing the driver's Final Destination on that exact same row.

import duckdb
query_fd = """
SELECT
    Driver,
    Time,
    Stop_Name,
    LAST_VALUE(Stop_Name) OVER(
        PARTITION BY Driver
        ORDER BY Time ASC
        ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS Final_Destination
FROM df_routes
ORDER BY Driver, Time ASC;
"""

duckdb.query(query_fd).df()

     Driver   Time    Stop_Name Final_Destination
0  Driver_A  08:00    Warehouse       Post Office
1  Driver_A  08:30  Coffee Shop       Post Office
2  Driver_A  09:00  Post Office       Post Office
3  Driver_B  10:00    Warehouse       Gas Station
4  Driver_B  11:00  Gas Station       Gas Station

In [18]:
import pandas as pd

df_sales = pd.DataFrame({
    'Emp_Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi'],
    'Revenue': [50000, 80000, 30000, 120000, 95000, 45000, 110000, 60000]
})

df_sales

  Emp_Name  Revenue
0    Alice    50000
1      Bob    80000
2  Charlie    30000
3    David   120000
4      Eve    95000
5    Frank    45000
6    Grace   110000
7    Heidi    60000

In [28]:
# The VP of Sales is calculating end-of-year bonuses. They hand you a dataset of every salesperson and their total revenue.
# They have two specific requests for the final report:
# 1. The Tiers: They want to divide the team into exactly 4 equal groups (Quartiles) based on revenue. The highest earners must be in Tier 1.
# 2. The Target to Beat: To motivate the team, they want a column that displays the revenue of the absolute #1 Top Performer pasted onto every single row, so everyone knows exactly what the high score was.

import duckdb
query_z = """
SELECT
    Emp_Name,
    Revenue,
    NTILE(4) OVER(ORDER BY Revenue DESC) AS Performance_Tier,
    FIRST_VALUE(Emp_Name) OVER(ORDER BY Revenue DESC) AS Top_Scorer
FROM df_sales;
"""
duckdb.query(query_z).df()

  Emp_Name  Revenue  Performance_Tier Top_Scorer
0    David   120000                 1      David
1    Grace   110000                 1      David
2      Eve    95000                 2      David
3      Bob    80000                 2      David
4    Heidi    60000                 3      David
5    Alice    50000                 3      David
6    Frank    45000                 4      David
7  Charlie    30000                 4      David